name: Translate

on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # ISO Language Codes: https://cloud.google.com/translate/docs/languages  
      - name: Adding README - Spanish
        uses: dephraiim/translate-readme@main
        with:
          LANG: es
      - name: Adding README - Portuguese
        uses: dephraiim/translate-readme@main
        with:
          LANG: pt
      - name: Adding README - French
        uses: dephraiim/translate-readme@main
        with:
          LANG: fr
      - name: Adding README - Italian
        uses: dephraiim/translate-readme@main
        with:
          LANG: it
      - name: Adding README - German
        uses: dephraiim/translate-readme@main
        with:
          LANG: de
